#
# Juicebox Crowdin credentials
#
'project_id': ${{ secrets.CROWDIN_PROJECT_ID }}
'api_token': ${{ secrets.CROWDIN_API_TOKEN }}
'base_path': '.'
'base_url': 'https://api.crowdin.com'

#
# Choose file structure in Crowdin
#
'preserve_hierarchy': true

#
# Files configuration
#
files:
  [
    {
      'source': 'src/locales/en/messages.po',
      'translation': 'src/locales/%two_letters_code%/%original_file_name%',
    },
  ]
