// List of all the eventIds that Fathom tracks
export const CREATE_FLOW = {
  DETAILS_NEXT_CTA: 'VMJSN0G5',
  CYCLES_NEXT_CTA: 'R95J73KA',
  TARGET_NEXT_CTA: 'BETQDHLF',
  PAYOUTS_NEXT_CTA: 'GWOTVPPZ',
  TOKEN_NEXT_CTA: 'HCVKOTXE',
  NFT_NEXT_CTA: 'NRV6ZYCX',
  RULES_NEXT_CTA: 'WVHD1406',
}

export const HOMEPAGE = {
  CREATE_A_PROJECT_CTA: 'DD4599PZ',
  CREATE_A_PROJECT_CTA_NEW: 'AM81SJ1N',
  EXPLORE_PROJECTS_CTA: 'W3ZVWUTC',
}

export const PROJECTS_PAGE = {
  CREATE_A_PROJECT_CTA: 'M3YATRAA',
}

export const PROJECT_PAGE = {
  PAY_CTA: 'PFJQKF7D',
}

export const TOP_NAV = {
  CREATE_A_PROJECT_CTA: 'LHWCLH9E',
  EXPLORE_CTA: 'YTTX60ZQ',
  DISCORD_CTA: 'PKIBZYTS',
  SEARCH_CTA: 'OJRCY4EI',
}
