name = "juicebox"
type = "webpack"
account_id = "dc724e5a3245a509f7a1bb7e16920e3f"
webpack_config = "webpack.config.js"
compatibility_date = "2021-12-11"
workers_dev = true

[vars]
ORIGIN_URL = "https://bafybeid6hizzc6wzb26nyjm4goadmup62sirg5lpgangocxqmjtwnvvyx4.on.fleek.co"
SUBGRAPH_URL = "https://api.studio.thegraph.com/query/9534/juicebox-rinkeby/v0.0.2"

[env.staging]
workers_dev = false
route = "dev.bananamilk.net/*"
zone_id = "206fc2d0e9542f44c72fede8077369af"

[env.staging.vars]
ORIGIN_URL = "https://bafybeid6hizzc6wzb26nyjm4goadmup62sirg5lpgangocxqmjtwnvvyx4.on.fleek.co"
SUBGRAPH_URL = "https://api.studio.thegraph.com/query/9534/juicebox-rinkeby/v0.0.2"

[env.production]
workers_dev = false
route = "juicebox.money/*"
zone_id = "206fc2d0e9542f44c72fede8077369af"

[env.production.vars]
ORIGIN_URL = "https://juice.on.fleek.co"
SUBGRAPH_URL = "https://api.studio.thegraph.com/query/9534/juicebox-rinkeby/v0.0.2"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
