name = "meta-tags"
workers_dev = true
type = "webpack"
account_id = "dc724e5a3245a509f7a1bb7e16920e3f"
webpack_config = "webpack.config.js"
compatibility_date = "2021-12-11"

[env.production]
# The ID of the domain to deploying to
zone_id = "$yourZoneId"

# The route pattern your Workers application will be served at
route = "example.com/*"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
