import '../styles/index.scss'
import { InitWrapper } from './InitWrapper'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <InitWrapper>{children}</InitWrapper>
      </body>
    </html>
  )
}
