module.exports = [
  "ExampleModAllocator",
  "ExampleETHUSDPriceFeed",
  "ExampleJuiceboxProject",
  "ExampleYielder",
  "ExampleFailingFundingCycleBallot",
  "YearnYielder",
  "Tickets",
  "DirectPaymentAddress",
  "ProxyPaymentAddress",
  "TokenRepresentationProxy",
  "Active3DaysFundingCycleBallot",
  "Active7DaysFundingCycleBallot",
  "Active14DaysFundingCycleBallot",
];
