export type CreatePage =
  | 'projectDetails'
  | 'fundingCycles'
  | 'treasurySetup'
  | 'fundingTarget'
  | 'payouts'
  | 'projectToken'
  | 'nftRewards'
  | 'reconfigurationRules'
  | 'reviewDeploy'
