name: Crowdin upload

on:
  push:
    branches:
      - main

  # manual trigger from Github UI - Action tab
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Extract translations
        run: 'yarn i18n:extract'

      - name: Upload to Crowdin
        uses: crowdin/github-action@1.4.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_translations: true
          download_translations: false
          project_id: '492549'
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: 'src/locales/messages.pot'
          translation: 'src/locales/%two_letters_code%/%original_file_name%'
