name: Crowdin upload

on:
  push:
    branches:
      - crowdin-integration

  # manual trigger from Github UI - Action tab
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Extract translations
        run: 'yarn i18n:compile'

      - name: Upload to Crowdin
        uses: crowdin/github-action@1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_translations: true
          download_translations: false
          project_id: '492549'
          # token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          token: '3483c7f56ed2018ec04cf6194de23e1d3552f34bff605bd092728781d0e88ec27d4af1a9ed10e433'
          source: 'src/locales/en/messages.po'
          translation: 'src/locales/%two_letters_code%/%original_file_name%'
