name: Crowdin upload

on:
  push:
    branches:
      - main

  # manual trigger from Github UI - Action tab
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Extract translations
        run: 'yarn i18n:compile'

      - name: Upload to Crowdin
        uses: crowdin/github-action@1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
        with:
          config: 'crowdin.yml'
          upload_translations: true
          download_translations: false
          source: 'src/locales/en/messages.po'
          translation: 'src/locales/%two_letters_code%/%original_file_name%'
