name: Deploy Migrations to Sepolia

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SEPOLIA_DB_PASSWORD }}
      SEPOLIA_PROJECT_ID: ${{ secrets.SEPOLIA_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $SEPOLIA_PROJECT_ID
          supabase db push
